import { Inter } from "next/font/google";
import { MantineWrapper } from "@/libs/MatineWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lecture14",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className="{inter.className}">
      <MantineWrapper>{children}</MantineWrapper>
     </body>
    </html>
  );
}
